### ISSUE TITLE
Precision is lost, and the id is recognized as a date.

### ISSUE THREAD

**Issue by fuzhengyin** [triggerdotdev/jsonhero-web#144]
```json
{
    "id": 1610521604143693812
}
```
url: [https://jsonhero.io/j/rFjT37bQM4sV/tree](https://jsonhero.io/j/rFjT37bQM4sV/tree)

<img width="1440" alt="截屏2023-01-04 18 15 06" src="https://user-images.githubusercontent.com/89236842/210533182-67fbd8b6-1c39-4f40-a541-978eefbf4ef8.png">

**Comment by matt-aitken** [comment]
Hi @fuzhengyin,

We always display the original data as parsed by `JSON.parse()` at the top of the panel (under id in this case). Further down are just alternative ways of thinking about the data based on our best guess.

What you're experiencing here is that JavaScript uses the double number type for all numbers, and it's not 100% accurate. It can represent integers up to 2^53 (9007199254740992) accurately, but anything above that isn't guaranteed. 

![What happens when JavaScript creates a number from your input](https://user-images.githubusercontent.com/10635986/210536759-2afed1cb-7b96-453e-8df1-33bc6e123902.png)

If you need to be able to accurately represent integers this large then you should use strings in JSON, and then in your code use BigInt(). [This page has good info on this topic](https://www.w3schools.com/js/js_bigint.asp). 

[This is a brilliant article](https://fabiensanglard.net/floating_point_visually_explained/) that explains floating point numbers in lots of detail.
